services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - nginx
    ports:
      - 8080:8080
    develop:
      watch:
        - action: sync
          path: .
          target: /app
  nginx:
    image: nginx:latest
